<h1 class="title">帮您找房</h1>
<div class="dashline"></div>

<div class="staticContent">
<p>房子找到了吗？如果长期没有找到合适的房子，又急需地方落脚，可以试试我们新推出的帮您 找房中介业务，但是请注意一下几点：</p>
<p>1 我们不是房产公司，所以没有办法保证特定地点特定时间必然找到。但要找个落脚地还是可以的。在条件允许的情况下，会尽量按照偏好的地点找。</p>
<p>2 需求合理，5000左右找单独公寓 机会几乎是为零的</p>
<p>3 我们找的一般是民宿，corridor通常情况下是没有源的。</p>
<p>4 找房成功后，我们收取半个月的房租作为中介费</p>


<p>如有任何疑义，可通过 info@zugefangzi.com 联系我们！谢谢！</p>
<div class='dashline' style="clear: both;width:900px;margin-top:20px;padding-bottom:10px;"></div>
<?php 
echo $this->form;
?>
</div>