<div class="pagination">
    
    
        
 <div class="paginationInfo">
       
       这里是  <?php echo $this->totalItemCount; ?> 条记录里的  <?php echo $this->firstItemNumber?>-<?php echo $this->lastItemNumber;?> 条
       <!-- <?php echo $this->current; ?>/<?php echo  $this->last; ?>  -->  
 </div>
 
 
 <div class="paginationNumbers">
 
        <div class="pageNext">
        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
               <a href="<?php echo $this->url(array('page' => $this->next)); ?>">下一页 </a> 
         <?php endif; ?>      
        <!-- Last page link 
        <?php if (isset($this->next)): ?>
              <a href="<?php echo  $this->url(array('page' => $this->last)); ?>">末页</a>
        <?php endif; ?>-->
        </div>
 
        
        <!-- Numbered page links -->
        <div class="pageNumbers">
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
            <?php else: ?>
            <span>
                <?php echo $page; ?></span>
            <?php endif; ?>
        <?php endforeach; ?>
        </div>
        
        
 
    <div class="pagePrev">
        <!-- First page link 
        <?php if (isset($this->previous)): ?>
          <a href="<?php echo  $this->url(array('page' => $this->first)); ?>">首页</a> 
    <?php endif; ?>-->
        <!-- Previous page link -->
    	<?php if (isset($this->previous)): ?>
              <a href="<?php echo  $this->url(array('page' => $this->previous)); ?>">上一页</a> 
              <?php endif; ?>
        </div>
        
        
        </div>
        
 
 
 </div>